name: release
on:
 push:
   tags:
     - "v*"
env:
  GO111MODULE: on
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run build
      run: make build
    - uses: docker/login-action@v1
      with:
        registry: https://ghcr.io
        username: choffmeister
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v3
      with:
        images: ghcr.io/choffmeister/git-describe-semver
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
      id: docker-meta
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Check Tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo ::set-output name=result::false
        else
          echo ::set-output name=result::true
        fi
      id: is_prerelease
    - uses: softprops/action-gh-release@v1
      with:
        prerelease: ${{ steps.is_prerelease.outputs.result }}
        files: build/*
